(define (problem envelope-prob)

    (:domain envelope)

    (:init
        (Balice_Palice_not_secret)
        (Balice_Palice_secret)
        (Balice_Pbob_not_secret)
        (Balice_Pbob_secret)
        (Bbob_Palice_not_secret)
        (Bbob_Palice_secret)
        (Bbob_Pbob_not_secret)
        (Bbob_Pbob_secret)
        (Palice_not_secret)
        (Palice_Palice_not_secret)
        (Palice_Palice_secret)
        (Palice_Pbob_not_secret)
        (Palice_Pbob_secret)
        (Palice_secret)
        (Pbob_not_secret)
        (Pbob_Palice_not_secret)
        (Pbob_Palice_secret)
        (Pbob_Pbob_not_secret)
        (Pbob_Pbob_secret)
        (Pbob_secret)
        (secret)
    )

    (:goal (and
        (Bbob_Balice_secret)
        (Bbob_Palice_secret)
        (Pbob_Balice_secret)
        (Pbob_Palice_secret)
    ))
)