(define (domain envelope)

    (:requirements :strips :conditional-effects)

    (:predicates
        (not_secret)
        (Balice_not_secret)
        (Balice_Balice_not_secret)
        (Balice_Balice_secret)
        (Balice_Bbob_not_secret)
        (Balice_Bbob_secret)
        (Balice_Palice_not_secret)
        (Balice_Palice_secret)
        (Balice_Pbob_not_secret)
        (Balice_Pbob_secret)
        (Balice_secret)
        (Bbob_not_secret)
        (Bbob_Balice_not_secret)
        (Bbob_Balice_secret)
        (Bbob_Bbob_not_secret)
        (Bbob_Bbob_secret)
        (Bbob_Palice_not_secret)
        (Bbob_Palice_secret)
        (Bbob_Pbob_not_secret)
        (Bbob_Pbob_secret)
        (Bbob_secret)
        (Palice_not_secret)
        (Palice_Balice_not_secret)
        (Palice_Balice_secret)
        (Palice_Bbob_not_secret)
        (Palice_Bbob_secret)
        (Palice_Palice_not_secret)
        (Palice_Palice_secret)
        (Palice_Pbob_not_secret)
        (Palice_Pbob_secret)
        (Palice_secret)
        (Pbob_not_secret)
        (Pbob_Balice_not_secret)
        (Pbob_Balice_secret)
        (Pbob_Bbob_not_secret)
        (Pbob_Bbob_secret)
        (Pbob_Palice_not_secret)
        (Pbob_Palice_secret)
        (Pbob_Pbob_not_secret)
        (Pbob_Pbob_secret)
        (Pbob_secret)
        (secret)
    )

    (:action check_alice
        :precondition (and )
        :effect (and
                    ; #12674: <==closure== 14259 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (Pbob_Palice_secret))

                    ; #14259: <==commonly_known== 65378 (neg)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (Pbob_Balice_secret))

                    ; #14324: <==closure== 80076 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Bbob_Palice_not_secret))

                    ; #16008: <==closure== 20775 (pos)
                    (when (and (Pbob_not_secret))
                          (Pbob_Palice_not_secret))

                    ; #19232: <==closure== 19498 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (Pbob_Palice_not_secret))

                    ; #19498: <==commonly_known== 55468 (neg)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (Pbob_Balice_not_secret))

                    ; #20049: <==closure== 24546 (pos)
                    (when (and (secret))
                          (Palice_secret))

                    ; #20775: <==commonly_known== 40690 (neg)
                    (when (and (Pbob_not_secret))
                          (Pbob_Balice_not_secret))

                    ; #24546: origin
                    (when (and (secret))
                          (Balice_secret))

                    ; #24552: <==commonly_known== 57148 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (Bbob_Balice_secret))

                    ; #29250: <==closure== 37606 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (Bbob_Palice_secret))

                    ; #31137: <==closure== 24552 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (Pbob_Balice_secret))

                    ; #31190: <==closure== 40818 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (Bbob_Palice_not_secret))

                    ; #33742: <==closure== 80076 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Pbob_Balice_not_secret))

                    ; #37606: <==commonly_known== 24546 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (Bbob_Balice_secret))

                    ; #39319: <==closure== 80076 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Pbob_Palice_not_secret))

                    ; #40818: <==commonly_known== 75626 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (Bbob_Balice_not_secret))

                    ; #41203: <==closure== 55146 (pos)
                    (when (and (not_secret))
                          (Palice_not_secret))

                    ; #41371: <==closure== 75626 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Palice_not_secret))

                    ; #42834: <==closure== 24552 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (Pbob_Palice_secret))

                    ; #49849: <==closure== 57148 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (Palice_secret))

                    ; #52335: <==closure== 37606 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (Pbob_Balice_secret))

                    ; #55146: origin
                    (when (and (not_secret))
                          (Balice_not_secret))

                    ; #55343: <==closure== 37606 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (Pbob_Palice_secret))

                    ; #57148: <==commonly_known== 24546 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (Balice_secret))

                    ; #62962: <==closure== 24552 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (Bbob_Palice_secret))

                    ; #69271: <==closure== 79278 (pos)
                    (when (and (Pbob_secret))
                          (Pbob_Palice_secret))

                    ; #75626: <==commonly_known== 55146 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Balice_not_secret))

                    ; #79278: <==commonly_known== 41593 (neg)
                    (when (and (Pbob_secret))
                          (Pbob_Balice_secret))

                    ; #80076: <==commonly_known== 55146 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Bbob_Balice_not_secret))

                    ; #85324: <==closure== 40818 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (Pbob_Palice_not_secret))

                    ; #89579: <==closure== 40818 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (Pbob_Balice_not_secret))

                    ; #13273: <==uncertain_firing== 24552 (pos)
                    (when (and (and (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))
                               (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))))
                          (not (Pbob_Palice_not_secret)))

                    ; #15654: <==negation-removal== 69271 (pos)
                    (when (and (Pbob_secret))
                          (not (Bbob_Balice_not_secret)))

                    ; #18260: <==negation-removal== 19498 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (not (Bbob_Palice_secret)))

                    ; #19656: <==negation-removal== 12674 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (not (Bbob_Balice_not_secret)))

                    ; #20356: <==unclosure== 65378 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Balice_not_secret)))

                    ; #20512: <==negation-removal== 80076 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Pbob_Palice_secret)))

                    ; #21426: <==unclosure== 65788 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Bbob_Palice_not_secret)))

                    ; #24961: <==unclosure== 43009 (neg)
                    (when (and (and (not (Pbob_secret))
                               (not (Bbob_secret))))
                          (not (Bbob_Balice_secret)))

                    ; #25006: <==unclosure== 41593 (neg)
                    (when (and (not (not_secret)))
                          (not (Balice_not_secret)))

                    ; #25108: <==unclosure== 13273 (neg)
                    (when (and (and (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))
                               (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))))
                          (not (Bbob_Balice_not_secret)))

                    ; #25359: <==negation-removal== 37606 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (not (Pbob_Palice_not_secret)))

                    ; #26281: <==negation-removal== 20775 (pos)
                    (when (and (Pbob_not_secret))
                          (not (Bbob_Palice_secret)))

                    ; #30589: <==negation-removal== 49849 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (not (Balice_not_secret)))

                    ; #32647: <==unclosure== 65788 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Bbob_Balice_not_secret)))

                    ; #32690: <==negation-removal== 16008 (pos)
                    (when (and (Pbob_not_secret))
                          (not (Bbob_Balice_secret)))

                    ; #33557: <==negation-removal== 57148 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (not (Palice_not_secret)))

                    ; #34618: <==negation-removal== 29250 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (not (Pbob_Balice_not_secret)))

                    ; #37443: <==unclosure== 43009 (neg)
                    (when (and (and (not (Pbob_secret))
                               (not (Bbob_secret))))
                          (not (Pbob_Balice_secret)))

                    ; #40125: <==negation-removal== 31190 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (not (Pbob_Balice_secret)))

                    ; #40366: <==negation-removal== 55343 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (not (Bbob_Balice_not_secret)))

                    ; #40690: <==uncertain_firing== 55146 (pos)
                    (when (and (not (secret)))
                          (not (Palice_secret)))

                    ; #40730: <==negation-removal== 14324 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Pbob_Balice_secret)))

                    ; #40799: <==negation-removal== 85324 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (not (Bbob_Balice_secret)))

                    ; #40807: <==negation-removal== 41371 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Balice_secret)))

                    ; #41593: <==uncertain_firing== 24546 (pos)
                    (when (and (not (not_secret)))
                          (not (Palice_not_secret)))

                    ; #43009: <==uncertain_firing== 80076 (pos)
                    (when (and (and (not (Pbob_secret))
                               (not (Bbob_secret))))
                          (not (Pbob_Palice_secret)))

                    ; #43409: <==negation-removal== 24546 (pos)
                    (when (and (secret))
                          (not (Palice_not_secret)))

                    ; #46314: <==unclosure== 13273 (neg)
                    (when (and (and (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))
                               (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))))
                          (not (Bbob_Palice_not_secret)))

                    ; #46986: <==negation-removal== 75626 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Palice_secret)))

                    ; #47029: <==negation-removal== 19232 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (not (Bbob_Balice_secret)))

                    ; #47364: <==uncertain_firing== 40818 (pos)
                    (when (and (and (not (Bbob_Balice_secret))
                               (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Pbob_Palice_secret)))

                    ; #48061: <==unclosure== 47364 (neg)
                    (when (and (and (not (Bbob_Balice_secret))
                               (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Bbob_Balice_secret)))

                    ; #49679: <==negation-removal== 62962 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (not (Pbob_Balice_not_secret)))

                    ; #51214: <==unclosure== 13273 (neg)
                    (when (and (and (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))
                               (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))))
                          (not (Pbob_Balice_not_secret)))

                    ; #53180: <==unclosure== 65788 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Pbob_Balice_not_secret)))

                    ; #54000: <==unclosure== 55468 (neg)
                    (when (and (and (not (Balice_secret))
                               (not (Palice_secret))))
                          (not (Balice_secret)))

                    ; #54606: <==negation-removal== 20049 (pos)
                    (when (and (secret))
                          (not (Balice_not_secret)))

                    ; #55468: <==uncertain_firing== 75626 (pos)
                    (when (and (and (not (Balice_secret))
                               (not (Palice_secret))))
                          (not (Palice_secret)))

                    ; #57859: <==negation-removal== 55146 (pos)
                    (when (and (not_secret))
                          (not (Palice_secret)))

                    ; #61933: <==negation-removal== 79278 (pos)
                    (when (and (Pbob_secret))
                          (not (Bbob_Palice_not_secret)))

                    ; #65378: <==uncertain_firing== 57148 (pos)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Palice_not_secret)))

                    ; #65536: <==negation-removal== 24552 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (not (Pbob_Palice_not_secret)))

                    ; #65570: <==negation-removal== 39319 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Bbob_Balice_secret)))

                    ; #65788: <==uncertain_firing== 37606 (pos)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Pbob_Palice_not_secret)))

                    ; #66600: <==unclosure== 40690 (neg)
                    (when (and (not (secret)))
                          (not (Balice_secret)))

                    ; #67398: <==negation-removal== 40818 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (not (Pbob_Palice_secret)))

                    ; #68920: <==negation-removal== 41203 (pos)
                    (when (and (not_secret))
                          (not (Balice_secret)))

                    ; #78663: <==negation-removal== 33742 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Bbob_Palice_secret)))

                    ; #78849: <==unclosure== 47364 (neg)
                    (when (and (and (not (Bbob_Balice_secret))
                               (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Bbob_Palice_secret)))

                    ; #79498: <==negation-removal== 89579 (pos)
                    (when (and (and (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)))
                          (not (Bbob_Palice_secret)))

                    ; #80213: <==negation-removal== 31137 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (not (Bbob_Palice_not_secret)))

                    ; #80511: <==unclosure== 43009 (neg)
                    (when (and (and (not (Pbob_secret))
                               (not (Bbob_secret))))
                          (not (Bbob_Palice_secret)))

                    ; #82878: <==negation-removal== 42834 (pos)
                    (when (and (and (Bbob_Balice_secret)
                               (Pbob_Palice_secret)
                               (Pbob_Balice_secret)
                               (Bbob_Palice_secret)))
                          (not (Bbob_Balice_not_secret)))

                    ; #84069: <==negation-removal== 52335 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (not (Bbob_Palice_not_secret)))

                    ; #86022: <==unclosure== 47364 (neg)
                    (when (and (and (not (Bbob_Balice_secret))
                               (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Pbob_Balice_secret)))

                    ; #86031: <==negation-removal== 14259 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (not (Bbob_Palice_not_secret)))))

    (:action check_bob
        :precondition (and )
        :effect (and
                    ; #13796: <==commonly_known== 98519 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Bbob_not_secret))

                    ; #14985: <==commonly_known== 98519 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Balice_Bbob_not_secret))

                    ; #25474: <==closure== 85038 (pos)
                    (when (and (Palice_secret))
                          (Palice_Pbob_secret))

                    ; #27641: <==commonly_known== 68362 (neg)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (Palice_Bbob_secret))

                    ; #28095: <==closure== 49233 (pos)
                    (when (and (secret))
                          (Pbob_secret))

                    ; #29411: <==closure== 14985 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Balice_Pbob_not_secret))

                    ; #32799: <==commonly_known== 82035 (neg)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)))
                          (Palice_Bbob_not_secret))

                    ; #36792: <==closure== 47017 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (Palice_Pbob_secret))

                    ; #36942: <==closure== 86177 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (Balice_Pbob_not_secret))

                    ; #42662: <==closure== 32799 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)))
                          (Palice_Pbob_not_secret))

                    ; #44941: <==closure== 47017 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (Balice_Pbob_secret))

                    ; #45113: <==closure== 13796 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Pbob_not_secret))

                    ; #47017: <==commonly_known== 62714 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (Balice_Bbob_secret))

                    ; #49233: origin
                    (when (and (secret))
                          (Bbob_secret))

                    ; #49831: <==commonly_known== 49233 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (Balice_Bbob_secret))

                    ; #57080: <==closure== 86177 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (Palice_Bbob_not_secret))

                    ; #58462: <==closure== 49831 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (Palice_Pbob_secret))

                    ; #58544: <==closure== 49831 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (Balice_Pbob_secret))

                    ; #62331: <==closure== 75200 (pos)
                    (when (and (Palice_not_secret))
                          (Palice_Pbob_not_secret))

                    ; #62714: <==commonly_known== 49233 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (Bbob_secret))

                    ; #72580: <==closure== 62714 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (Pbob_secret))

                    ; #73027: <==closure== 86177 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (Palice_Pbob_not_secret))

                    ; #73516: <==closure== 14985 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Palice_Pbob_not_secret))

                    ; #75200: <==commonly_known== 77611 (neg)
                    (when (and (Palice_not_secret))
                          (Palice_Bbob_not_secret))

                    ; #77745: <==closure== 14985 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Palice_Bbob_not_secret))

                    ; #80183: <==closure== 98519 (pos)
                    (when (and (not_secret))
                          (Pbob_not_secret))

                    ; #82750: <==closure== 49831 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (Palice_Bbob_secret))

                    ; #85038: <==commonly_known== 78137 (neg)
                    (when (and (Palice_secret))
                          (Palice_Bbob_secret))

                    ; #86177: <==commonly_known== 13796 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (Balice_Bbob_not_secret))

                    ; #91735: <==closure== 47017 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (Palice_Bbob_secret))

                    ; #92899: <==closure== 27641 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (Palice_Pbob_secret))

                    ; #98519: origin
                    (when (and (not_secret))
                          (Bbob_not_secret))

                    ; #11842: <==negation-removal== 58544 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (not (Palice_Bbob_not_secret)))

                    ; #12212: <==negation-removal== 92899 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (not (Balice_Bbob_not_secret)))

                    ; #12720: <==negation-removal== 45113 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Bbob_secret)))

                    ; #15484: <==uncertain_firing== 49831 (pos)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Palice_Pbob_not_secret)))

                    ; #20430: <==negation-removal== 28095 (pos)
                    (when (and (secret))
                          (not (Bbob_not_secret)))

                    ; #20503: <==negation-removal== 82750 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (not (Balice_Pbob_not_secret)))

                    ; #24069: <==negation-removal== 62714 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (not (Pbob_not_secret)))

                    ; #25659: <==negation-removal== 58462 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (not (Balice_Bbob_not_secret)))

                    ; #27398: <==negation-removal== 77745 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Balice_Pbob_secret)))

                    ; #28198: <==unclosure== 15484 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Balice_Bbob_not_secret)))

                    ; #29389: <==negation-removal== 80183 (pos)
                    (when (and (not_secret))
                          (not (Bbob_secret)))

                    ; #29522: <==negation-removal== 29411 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Palice_Bbob_secret)))

                    ; #31102: <==unclosure== 87094 (neg)
                    (when (and (and (not (Balice_secret))
                               (not (Palice_secret))))
                          (not (Balice_Bbob_secret)))

                    ; #32698: <==unclosure== 15484 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Balice_Pbob_not_secret)))

                    ; #34085: <==negation-removal== 49233 (pos)
                    (when (and (secret))
                          (not (Pbob_not_secret)))

                    ; #36781: <==negation-removal== 86177 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (not (Palice_Pbob_secret)))

                    ; #36867: <==unclosure== 78137 (neg)
                    (when (and (not (not_secret)))
                          (not (Bbob_not_secret)))

                    ; #37025: <==unclosure== 87094 (neg)
                    (when (and (and (not (Balice_secret))
                               (not (Palice_secret))))
                          (not (Palice_Bbob_secret)))

                    ; #38935: <==negation-removal== 73027 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (not (Balice_Bbob_secret)))

                    ; #41409: <==negation-removal== 27641 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (not (Balice_Pbob_not_secret)))

                    ; #42945: <==unclosure== 71578 (neg)
                    (when (and (and (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))
                               (not (Balice_Bbob_secret))))
                          (not (Palice_Bbob_secret)))

                    ; #44145: <==negation-removal== 98519 (pos)
                    (when (and (not_secret))
                          (not (Pbob_secret)))

                    ; #45509: <==unclosure== 68362 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Bbob_not_secret)))

                    ; #46519: <==negation-removal== 36792 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (not (Balice_Bbob_not_secret)))

                    ; #46930: <==unclosure== 77611 (neg)
                    (when (and (not (secret)))
                          (not (Bbob_secret)))

                    ; #51303: <==negation-removal== 36942 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (not (Palice_Bbob_secret)))

                    ; #52619: <==negation-removal== 91735 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (not (Balice_Pbob_not_secret)))

                    ; #53289: <==negation-removal== 32799 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)))
                          (not (Balice_Pbob_secret)))

                    ; #54136: <==negation-removal== 75200 (pos)
                    (when (and (Palice_not_secret))
                          (not (Balice_Pbob_secret)))

                    ; #57306: <==unclosure== 71578 (neg)
                    (when (and (and (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))
                               (not (Balice_Bbob_secret))))
                          (not (Balice_Bbob_secret)))

                    ; #60156: <==negation-removal== 72580 (pos)
                    (when (and (and (Pbob_secret)
                               (Bbob_secret)))
                          (not (Bbob_not_secret)))

                    ; #62906: <==negation-removal== 85038 (pos)
                    (when (and (Palice_secret))
                          (not (Balice_Pbob_not_secret)))

                    ; #64160: <==unclosure== 82035 (neg)
                    (when (and (and (not (Pbob_secret))
                               (not (Bbob_secret))))
                          (not (Bbob_secret)))

                    ; #65745: <==negation-removal== 42662 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)))
                          (not (Balice_Bbob_secret)))

                    ; #68362: <==uncertain_firing== 62714 (pos)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Pbob_not_secret)))

                    ; #69761: <==negation-removal== 57080 (pos)
                    (when (and (and (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Balice_Bbob_not_secret)))
                          (not (Balice_Pbob_secret)))

                    ; #71199: <==negation-removal== 49831 (pos)
                    (when (and (and (Balice_secret)
                               (Palice_secret)))
                          (not (Palice_Pbob_not_secret)))

                    ; #71578: <==uncertain_firing== 86177 (pos)
                    (when (and (and (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))
                               (not (Balice_Bbob_secret))))
                          (not (Palice_Pbob_secret)))

                    ; #72092: <==negation-removal== 44941 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (not (Palice_Bbob_not_secret)))

                    ; #73269: <==negation-removal== 47017 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)
                               (Balice_Bbob_secret)))
                          (not (Palice_Pbob_not_secret)))

                    ; #74165: <==negation-removal== 62331 (pos)
                    (when (and (Palice_not_secret))
                          (not (Balice_Bbob_secret)))

                    ; #74982: <==unclosure== 15484 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Palice_Bbob_not_secret)))

                    ; #75153: <==unclosure== 98017 (neg)
                    (when (and (and (not (Palice_Bbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Balice_Bbob_not_secret))))
                          (not (Balice_Pbob_not_secret)))

                    ; #77596: <==unclosure== 98017 (neg)
                    (when (and (and (not (Palice_Bbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Balice_Bbob_not_secret))))
                          (not (Palice_Bbob_not_secret)))

                    ; #77611: <==uncertain_firing== 98519 (pos)
                    (when (and (not (secret)))
                          (not (Pbob_secret)))

                    ; #78137: <==uncertain_firing== 49233 (pos)
                    (when (and (not (not_secret)))
                          (not (Pbob_not_secret)))

                    ; #78345: <==unclosure== 98017 (neg)
                    (when (and (and (not (Palice_Bbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Balice_Bbob_not_secret))))
                          (not (Balice_Bbob_not_secret)))

                    ; #82035: <==uncertain_firing== 13796 (pos)
                    (when (and (and (not (Pbob_secret))
                               (not (Bbob_secret))))
                          (not (Pbob_secret)))

                    ; #82587: <==negation-removal== 13796 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Pbob_secret)))

                    ; #84029: <==unclosure== 87094 (neg)
                    (when (and (and (not (Balice_secret))
                               (not (Palice_secret))))
                          (not (Balice_Pbob_secret)))

                    ; #85748: <==unclosure== 71578 (neg)
                    (when (and (and (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))
                               (not (Balice_Bbob_secret))))
                          (not (Balice_Pbob_secret)))

                    ; #87094: <==uncertain_firing== 14985 (pos)
                    (when (and (and (not (Balice_secret))
                               (not (Palice_secret))))
                          (not (Palice_Pbob_secret)))

                    ; #87251: <==negation-removal== 14985 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Palice_Pbob_secret)))

                    ; #88627: <==negation-removal== 25474 (pos)
                    (when (and (Palice_secret))
                          (not (Balice_Bbob_not_secret)))

                    ; #91253: <==negation-removal== 73516 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Balice_Bbob_secret)))

                    ; #98017: <==uncertain_firing== 47017 (pos)
                    (when (and (and (not (Palice_Bbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Balice_Bbob_not_secret))))
                          (not (Palice_Pbob_not_secret)))))

)