(define (domain envelope)

    (:requirements :strips :conditional-effects)

    (:predicates
        (not_secret)
        (Balice_not_secret)
        (Balice_Balice_not_secret)
        (Balice_Balice_secret)
        (Balice_Bbob_not_secret)
        (Balice_Bbob_secret)
        (Balice_Palice_not_secret)
        (Balice_Palice_secret)
        (Balice_Pbob_not_secret)
        (Balice_Pbob_secret)
        (Balice_secret)
        (Bbob_not_secret)
        (Bbob_Balice_not_secret)
        (Bbob_Balice_secret)
        (Bbob_Bbob_not_secret)
        (Bbob_Bbob_secret)
        (Bbob_Palice_not_secret)
        (Bbob_Palice_secret)
        (Bbob_Pbob_not_secret)
        (Bbob_Pbob_secret)
        (Bbob_secret)
        (Palice_not_secret)
        (Palice_Balice_not_secret)
        (Palice_Balice_secret)
        (Palice_Bbob_not_secret)
        (Palice_Bbob_secret)
        (Palice_Palice_not_secret)
        (Palice_Palice_secret)
        (Palice_Pbob_not_secret)
        (Palice_Pbob_secret)
        (Palice_secret)
        (Pbob_not_secret)
        (Pbob_Balice_not_secret)
        (Pbob_Balice_secret)
        (Pbob_Bbob_not_secret)
        (Pbob_Bbob_secret)
        (Pbob_Palice_not_secret)
        (Pbob_Palice_secret)
        (Pbob_Pbob_not_secret)
        (Pbob_Pbob_secret)
        (Pbob_secret)
        (secret)
    )

    (:action check_alice
        :precondition (and )
        :effect (and
                    ; #22070: <==commonly_known== 32548 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)))
                          (Bbob_Balice_not_secret))

                    ; #22304: <==closure== 72240 (pos)
                    (when (and (not_secret))
                          (Palice_not_secret))

                    ; #27474: <==closure== 32548 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Palice_not_secret))

                    ; #28636: <==commonly_known== 44939 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (Bbob_Balice_secret))

                    ; #32548: <==commonly_known== 72240 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Balice_not_secret))

                    ; #32682: <==closure== 22070 (pos)
                    (when (and (and (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (Pbob_Palice_not_secret))

                    ; #37949: <==closure== 79000 (pos)
                    (when (and (Pbob_not_secret))
                          (Pbob_Palice_not_secret))

                    ; #44443: <==closure== 44746 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (Palice_secret))

                    ; #44746: <==commonly_known== 44939 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (Balice_secret))

                    ; #44939: origin
                    (when (and (secret))
                          (Balice_secret))

                    ; #45086: <==closure== 22070 (pos)
                    (when (and (and (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (Pbob_Balice_not_secret))

                    ; #48357: <==closure== 28636 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (Pbob_Balice_secret))

                    ; #49043: <==closure== 75049 (pos)
                    (when (and (Pbob_secret))
                          (Pbob_Palice_secret))

                    ; #50188: <==closure== 44939 (pos)
                    (when (and (secret))
                          (Palice_secret))

                    ; #53553: <==closure== 22070 (pos)
                    (when (and (and (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (Bbob_Palice_not_secret))

                    ; #55191: <==commonly_known== 26627 (neg)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)))
                          (Pbob_Balice_not_secret))

                    ; #60619: <==closure== 73122 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Pbob_Balice_not_secret))

                    ; #72240: origin
                    (when (and (not_secret))
                          (Balice_not_secret))

                    ; #72672: <==commonly_known== 60331 (neg)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (Pbob_Balice_secret))

                    ; #73122: <==commonly_known== 72240 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Bbob_Balice_not_secret))

                    ; #73149: <==commonly_known== 44746 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (Bbob_Balice_secret))

                    ; #75049: <==commonly_known== 13420 (neg)
                    (when (and (Pbob_secret))
                          (Pbob_Balice_secret))

                    ; #76084: <==closure== 28636 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (Bbob_Palice_secret))

                    ; #76311: <==closure== 73149 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (Pbob_Palice_secret))

                    ; #78738: <==closure== 72672 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (Pbob_Palice_secret))

                    ; #79000: <==commonly_known== 80916 (neg)
                    (when (and (Pbob_not_secret))
                          (Pbob_Balice_not_secret))

                    ; #80704: <==closure== 73149 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (Bbob_Palice_secret))

                    ; #81646: <==closure== 73122 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Bbob_Palice_not_secret))

                    ; #84647: <==closure== 55191 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)))
                          (Pbob_Palice_not_secret))

                    ; #89743: <==closure== 73122 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Pbob_Palice_not_secret))

                    ; #90301: <==closure== 28636 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (Pbob_Palice_secret))

                    ; #91601: <==closure== 73149 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (Pbob_Balice_secret))

                    ; #12200: <==negation-removal== 79000 (pos)
                    (when (and (Pbob_not_secret))
                          (not (Bbob_Palice_secret)))

                    ; #13420: <==uncertain_firing== 44939 (pos)
                    (when (and (not (not_secret)))
                          (not (Palice_not_secret)))

                    ; #13773: <==negation-removal== 32548 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Palice_secret)))

                    ; #15158: <==negation-removal== 73122 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Pbob_Palice_secret)))

                    ; #15514: <==negation-removal== 50188 (pos)
                    (when (and (secret))
                          (not (Balice_not_secret)))

                    ; #16124: <==negation-removal== 55191 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)))
                          (not (Bbob_Palice_secret)))

                    ; #18298: <==negation-removal== 49043 (pos)
                    (when (and (Pbob_secret))
                          (not (Bbob_Balice_not_secret)))

                    ; #18754: <==negation-removal== 37949 (pos)
                    (when (and (Pbob_not_secret))
                          (not (Bbob_Balice_secret)))

                    ; #18811: <==unclosure== 13420 (neg)
                    (when (and (not (not_secret)))
                          (not (Balice_not_secret)))

                    ; #26627: <==uncertain_firing== 32548 (pos)
                    (when (and (and (not (Palice_secret))
                               (not (Balice_secret))))
                          (not (Palice_secret)))

                    ; #30625: <==negation-removal== 60619 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Bbob_Palice_secret)))

                    ; #31138: <==negation-removal== 72240 (pos)
                    (when (and (not_secret))
                          (not (Palice_secret)))

                    ; #31879: <==negation-removal== 28636 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (not (Pbob_Palice_not_secret)))

                    ; #35064: <==negation-removal== 27474 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Balice_secret)))

                    ; #35902: <==unclosure== 80916 (neg)
                    (when (and (not (secret)))
                          (not (Balice_secret)))

                    ; #37285: <==negation-removal== 44746 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (not (Palice_not_secret)))

                    ; #37546: <==unclosure== 38707 (neg)
                    (when (and (and (not (Bbob_secret))
                               (not (Pbob_secret))))
                          (not (Pbob_Balice_secret)))

                    ; #37786: <==uncertain_firing== 73149 (pos)
                    (when (and (and (not (Pbob_Palice_not_secret))
                               (not (Bbob_Balice_not_secret))
                               (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))))
                          (not (Pbob_Palice_not_secret)))

                    ; #37999: <==negation-removal== 53553 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (not (Pbob_Balice_secret)))

                    ; #38707: <==uncertain_firing== 73122 (pos)
                    (when (and (and (not (Bbob_secret))
                               (not (Pbob_secret))))
                          (not (Pbob_Palice_secret)))

                    ; #38755: <==unclosure== 54994 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Bbob_Balice_not_secret)))

                    ; #41909: <==unclosure== 37786 (neg)
                    (when (and (and (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))
                               (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))))
                          (not (Bbob_Balice_not_secret)))

                    ; #45926: <==negation-removal== 72672 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (not (Bbob_Palice_not_secret)))

                    ; #47020: <==negation-removal== 22304 (pos)
                    (when (and (not_secret))
                          (not (Balice_secret)))

                    ; #47675: <==negation-removal== 45086 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (not (Bbob_Palice_secret)))

                    ; #48540: <==negation-removal== 73149 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (not (Pbob_Palice_not_secret)))

                    ; #49271: <==negation-removal== 48357 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (not (Bbob_Palice_not_secret)))

                    ; #53520: <==negation-removal== 44443 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (not (Balice_not_secret)))

                    ; #54519: <==negation-removal== 76084 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (not (Pbob_Balice_not_secret)))

                    ; #54567: <==unclosure== 37786 (neg)
                    (when (and (and (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))
                               (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))))
                          (not (Bbob_Palice_not_secret)))

                    ; #54994: <==uncertain_firing== 28636 (pos)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Pbob_Palice_not_secret)))

                    ; #55509: <==unclosure== 38707 (neg)
                    (when (and (and (not (Bbob_secret))
                               (not (Pbob_secret))))
                          (not (Bbob_Palice_secret)))

                    ; #55563: <==negation-removal== 81646 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Pbob_Balice_secret)))

                    ; #56566: <==negation-removal== 91601 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (not (Bbob_Palice_not_secret)))

                    ; #57400: <==uncertain_firing== 22070 (pos)
                    (when (and (and (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Pbob_Palice_secret)))

                    ; #57664: <==negation-removal== 75049 (pos)
                    (when (and (Pbob_secret))
                          (not (Bbob_Palice_not_secret)))

                    ; #59625: <==unclosure== 57400 (neg)
                    (when (and (and (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Pbob_Balice_secret)))

                    ; #60331: <==uncertain_firing== 44746 (pos)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Palice_not_secret)))

                    ; #61669: <==unclosure== 57400 (neg)
                    (when (and (and (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Bbob_Palice_secret)))

                    ; #64053: <==negation-removal== 89743 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Bbob_Balice_secret)))

                    ; #68952: <==negation-removal== 76311 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (not (Bbob_Balice_not_secret)))

                    ; #72344: <==unclosure== 37786 (neg)
                    (when (and (and (not (Bbob_Balice_not_secret))
                               (not (Pbob_Palice_not_secret))
                               (not (Pbob_Balice_not_secret))
                               (not (Bbob_Palice_not_secret))))
                          (not (Pbob_Balice_not_secret)))

                    ; #73158: <==negation-removal== 22070 (pos)
                    (when (and (and (Bbob_Balice_not_secret)
                               (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (not (Pbob_Palice_secret)))

                    ; #73315: <==unclosure== 26627 (neg)
                    (when (and (and (not (Palice_secret))
                               (not (Balice_secret))))
                          (not (Balice_secret)))

                    ; #75280: <==unclosure== 54994 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Pbob_Balice_not_secret)))

                    ; #78906: <==unclosure== 54994 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Bbob_Palice_not_secret)))

                    ; #79778: <==negation-removal== 90301 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (not (Bbob_Balice_not_secret)))

                    ; #80498: <==negation-removal== 84647 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Pbob_Balice_not_secret)))
                          (not (Bbob_Balice_secret)))

                    ; #80916: <==uncertain_firing== 72240 (pos)
                    (when (and (not (secret)))
                          (not (Palice_secret)))

                    ; #81159: <==unclosure== 38707 (neg)
                    (when (and (and (not (Bbob_secret))
                               (not (Pbob_secret))))
                          (not (Bbob_Balice_secret)))

                    ; #81493: <==unclosure== 57400 (neg)
                    (when (and (and (not (Pbob_Palice_secret))
                               (not (Pbob_Balice_secret))
                               (not (Bbob_Balice_secret))
                               (not (Bbob_Palice_secret))))
                          (not (Bbob_Balice_secret)))

                    ; #82410: <==unclosure== 60331 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Balice_not_secret)))

                    ; #82657: <==negation-removal== 32682 (pos)
                    (when (and (and (Pbob_Palice_not_secret)
                               (Bbob_Balice_not_secret)
                               (Pbob_Balice_not_secret)
                               (Bbob_Palice_not_secret)))
                          (not (Bbob_Balice_secret)))

                    ; #86915: <==negation-removal== 80704 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Bbob_Palice_secret)
                               (Bbob_Balice_secret)
                               (Pbob_Balice_secret)))
                          (not (Pbob_Balice_not_secret)))

                    ; #87884: <==negation-removal== 44939 (pos)
                    (when (and (secret))
                          (not (Palice_not_secret)))

                    ; #90988: <==negation-removal== 78738 (pos)
                    (when (and (and (Pbob_Palice_secret)
                               (Pbob_Balice_secret)))
                          (not (Bbob_Balice_not_secret)))))

    (:action check_bob
        :precondition (and )
        :effect (and
                    ; #16356: <==closure== 89095 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (Palice_Pbob_not_secret))

                    ; #16575: <==closure== 23929 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (Palice_Pbob_secret))

                    ; #17714: <==closure== 89095 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (Palice_Bbob_not_secret))

                    ; #17932: <==closure== 64353 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (Balice_Pbob_secret))

                    ; #22504: <==commonly_known== 53263 (pos)
                    (when (and (and (Balice_Bbob_secret)
                               (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (Balice_Bbob_secret))

                    ; #23410: <==closure== 89095 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (Balice_Pbob_not_secret))

                    ; #23465: <==closure== 92032 (pos)
                    (when (and (secret))
                          (Pbob_secret))

                    ; #23929: <==commonly_known== 69505 (neg)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (Palice_Bbob_secret))

                    ; #26461: <==closure== 61679 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Balice_Pbob_not_secret))

                    ; #35482: <==commonly_known== 38754 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Bbob_not_secret))

                    ; #36748: <==commonly_known== 54066 (neg)
                    (when (and (Palice_not_secret))
                          (Palice_Bbob_not_secret))

                    ; #38754: origin
                    (when (and (not_secret))
                          (Bbob_not_secret))

                    ; #43282: <==closure== 22504 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Balice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (Palice_Bbob_secret))

                    ; #45442: <==closure== 36748 (pos)
                    (when (and (Palice_not_secret))
                          (Palice_Pbob_not_secret))

                    ; #47586: <==closure== 61679 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Palice_Bbob_not_secret))

                    ; #49018: <==closure== 35482 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (Pbob_not_secret))

                    ; #53263: <==commonly_known== 92032 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (Bbob_secret))

                    ; #60937: <==closure== 64353 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (Palice_Bbob_secret))

                    ; #61679: <==commonly_known== 38754 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Balice_Bbob_not_secret))

                    ; #63542: <==closure== 61679 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (Palice_Pbob_not_secret))

                    ; #63716: <==commonly_known== 26105 (neg)
                    (when (and (Palice_secret))
                          (Palice_Bbob_secret))

                    ; #64353: <==commonly_known== 92032 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (Balice_Bbob_secret))

                    ; #64828: <==closure== 53263 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (Pbob_secret))

                    ; #68161: <==closure== 22504 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Balice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (Palice_Pbob_secret))

                    ; #69345: <==closure== 64353 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (Palice_Pbob_secret))

                    ; #74466: <==closure== 38754 (pos)
                    (when (and (not_secret))
                          (Pbob_not_secret))

                    ; #78270: <==commonly_known== 82527 (neg)
                    (when (and (and (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (Palice_Bbob_not_secret))

                    ; #83857: <==closure== 78270 (pos)
                    (when (and (and (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (Palice_Pbob_not_secret))

                    ; #89095: <==commonly_known== 35482 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)
                               (Palice_Pbob_not_secret)))
                          (Balice_Bbob_not_secret))

                    ; #89759: <==closure== 63716 (pos)
                    (when (and (Palice_secret))
                          (Palice_Pbob_secret))

                    ; #91438: <==closure== 22504 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Balice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (Balice_Pbob_secret))

                    ; #92032: origin
                    (when (and (secret))
                          (Bbob_secret))

                    ; #10527: <==negation-removal== 23929 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (not (Balice_Pbob_not_secret)))

                    ; #11532: <==negation-removal== 89095 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (not (Palice_Pbob_secret)))

                    ; #12763: <==negation-removal== 64828 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (not (Bbob_not_secret)))

                    ; #13908: <==unclosure== 32554 (neg)
                    (when (and (and (not (Balice_Bbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Palice_Bbob_not_secret))))
                          (not (Balice_Pbob_not_secret)))

                    ; #14597: <==unclosure== 34673 (neg)
                    (when (and (and (not (Balice_Bbob_secret))
                               (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))))
                          (not (Balice_Pbob_secret)))

                    ; #18584: <==negation-removal== 22504 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Balice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (not (Palice_Pbob_not_secret)))

                    ; #19958: <==unclosure== 32554 (neg)
                    (when (and (and (not (Balice_Bbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Palice_Bbob_not_secret))))
                          (not (Balice_Bbob_not_secret)))

                    ; #20665: <==unclosure== 43432 (neg)
                    (when (and (and (not (Palice_secret))
                               (not (Balice_secret))))
                          (not (Balice_Pbob_secret)))

                    ; #20859: <==negation-removal== 35482 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Pbob_secret)))

                    ; #22249: <==unclosure== 75264 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Balice_Bbob_not_secret)))

                    ; #23158: <==unclosure== 69505 (neg)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Bbob_not_secret)))

                    ; #23568: <==negation-removal== 60937 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (not (Balice_Pbob_not_secret)))

                    ; #23771: <==negation-removal== 36748 (pos)
                    (when (and (Palice_not_secret))
                          (not (Balice_Pbob_secret)))

                    ; #25103: <==negation-removal== 16575 (pos)
                    (when (and (and (Palice_Bbob_secret)
                               (Palice_Pbob_secret)))
                          (not (Balice_Bbob_not_secret)))

                    ; #26105: <==uncertain_firing== 92032 (pos)
                    (when (and (not (not_secret)))
                          (not (Pbob_not_secret)))

                    ; #26250: <==negation-removal== 74466 (pos)
                    (when (and (not_secret))
                          (not (Bbob_secret)))

                    ; #30395: <==negation-removal== 23410 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (not (Palice_Bbob_secret)))

                    ; #31463: <==negation-removal== 17714 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (not (Balice_Pbob_secret)))

                    ; #31707: <==unclosure== 43432 (neg)
                    (when (and (and (not (Palice_secret))
                               (not (Balice_secret))))
                          (not (Palice_Bbob_secret)))

                    ; #32554: <==uncertain_firing== 22504 (pos)
                    (when (and (and (not (Balice_Bbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Palice_Bbob_not_secret))
                               (not (Palice_Pbob_not_secret))))
                          (not (Palice_Pbob_not_secret)))

                    ; #33342: <==negation-removal== 64353 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (not (Palice_Pbob_not_secret)))

                    ; #34673: <==uncertain_firing== 89095 (pos)
                    (when (and (and (not (Palice_Bbob_secret))
                               (not (Balice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))))
                          (not (Palice_Pbob_secret)))

                    ; #36366: <==unclosure== 75264 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Balice_Pbob_not_secret)))

                    ; #41458: <==negation-removal== 63716 (pos)
                    (when (and (Palice_secret))
                          (not (Balice_Pbob_not_secret)))

                    ; #42287: <==negation-removal== 89759 (pos)
                    (when (and (Palice_secret))
                          (not (Balice_Bbob_not_secret)))

                    ; #43432: <==uncertain_firing== 61679 (pos)
                    (when (and (and (not (Palice_secret))
                               (not (Balice_secret))))
                          (not (Palice_Pbob_secret)))

                    ; #47914: <==negation-removal== 63542 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Balice_Bbob_secret)))

                    ; #48028: <==negation-removal== 47586 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Balice_Pbob_secret)))

                    ; #48380: <==negation-removal== 17932 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (not (Palice_Bbob_not_secret)))

                    ; #50222: <==negation-removal== 68161 (pos)
                    (when (and (and (Balice_Bbob_secret)
                               (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (not (Balice_Bbob_not_secret)))

                    ; #50404: <==negation-removal== 26461 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Palice_Bbob_secret)))

                    ; #50750: <==negation-removal== 16356 (pos)
                    (when (and (and (Balice_Bbob_not_secret)
                               (Balice_Pbob_not_secret)
                               (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (not (Balice_Bbob_secret)))

                    ; #51275: <==unclosure== 82527 (neg)
                    (when (and (and (not (Bbob_secret))
                               (not (Pbob_secret))))
                          (not (Bbob_secret)))

                    ; #52753: <==negation-removal== 23465 (pos)
                    (when (and (secret))
                          (not (Bbob_not_secret)))

                    ; #52851: <==negation-removal== 45442 (pos)
                    (when (and (Palice_not_secret))
                          (not (Balice_Bbob_secret)))

                    ; #54066: <==uncertain_firing== 38754 (pos)
                    (when (and (not (secret)))
                          (not (Pbob_secret)))

                    ; #54273: <==negation-removal== 78270 (pos)
                    (when (and (and (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (not (Balice_Pbob_secret)))

                    ; #55945: <==negation-removal== 61679 (pos)
                    (when (and (and (Palice_not_secret)
                               (Balice_not_secret)))
                          (not (Palice_Pbob_secret)))

                    ; #58353: <==unclosure== 43432 (neg)
                    (when (and (and (not (Palice_secret))
                               (not (Balice_secret))))
                          (not (Balice_Bbob_secret)))

                    ; #58616: <==negation-removal== 43282 (pos)
                    (when (and (and (Balice_Bbob_secret)
                               (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (not (Balice_Pbob_not_secret)))

                    ; #61122: <==negation-removal== 91438 (pos)
                    (when (and (and (Balice_Bbob_secret)
                               (Palice_Bbob_secret)
                               (Palice_Pbob_secret)
                               (Balice_Pbob_secret)))
                          (not (Palice_Bbob_not_secret)))

                    ; #64079: <==unclosure== 34673 (neg)
                    (when (and (and (not (Balice_Bbob_secret))
                               (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))))
                          (not (Palice_Bbob_secret)))

                    ; #64452: <==negation-removal== 92032 (pos)
                    (when (and (secret))
                          (not (Pbob_not_secret)))

                    ; #66663: <==unclosure== 34673 (neg)
                    (when (and (and (not (Balice_Bbob_secret))
                               (not (Palice_Bbob_secret))
                               (not (Palice_Pbob_secret))
                               (not (Balice_Pbob_secret))))
                          (not (Balice_Bbob_secret)))

                    ; #68222: <==unclosure== 54066 (neg)
                    (when (and (not (secret)))
                          (not (Bbob_secret)))

                    ; #69505: <==uncertain_firing== 53263 (pos)
                    (when (and (and (not (Bbob_not_secret))
                               (not (Pbob_not_secret))))
                          (not (Pbob_not_secret)))

                    ; #71226: <==negation-removal== 38754 (pos)
                    (when (and (not_secret))
                          (not (Pbob_secret)))

                    ; #71692: <==negation-removal== 69345 (pos)
                    (when (and (and (Palice_secret)
                               (Balice_secret)))
                          (not (Balice_Bbob_not_secret)))

                    ; #75264: <==uncertain_firing== 64353 (pos)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Palice_Pbob_not_secret)))

                    ; #79306: <==negation-removal== 53263 (pos)
                    (when (and (and (Bbob_secret)
                               (Pbob_secret)))
                          (not (Pbob_not_secret)))

                    ; #79738: <==unclosure== 32554 (neg)
                    (when (and (and (not (Balice_Bbob_not_secret))
                               (not (Balice_Pbob_not_secret))
                               (not (Palice_Pbob_not_secret))
                               (not (Palice_Bbob_not_secret))))
                          (not (Palice_Bbob_not_secret)))

                    ; #79808: <==unclosure== 26105 (neg)
                    (when (and (not (not_secret)))
                          (not (Bbob_not_secret)))

                    ; #80515: <==negation-removal== 49018 (pos)
                    (when (and (and (Bbob_not_secret)
                               (Pbob_not_secret)))
                          (not (Bbob_secret)))

                    ; #82527: <==uncertain_firing== 35482 (pos)
                    (when (and (and (not (Bbob_secret))
                               (not (Pbob_secret))))
                          (not (Pbob_secret)))

                    ; #82966: <==negation-removal== 83857 (pos)
                    (when (and (and (Palice_Pbob_not_secret)
                               (Palice_Bbob_not_secret)))
                          (not (Balice_Bbob_secret)))

                    ; #89698: <==unclosure== 75264 (neg)
                    (when (and (and (not (Palice_not_secret))
                               (not (Balice_not_secret))))
                          (not (Palice_Bbob_not_secret)))))

)